version: '3.8'
services:
  app:
    build: .
    command: flask run --host=0.0.0.0 --reload --extra-files /app/**/*.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: run.py
      FLASK_RUN_HOST: 0.0.0.0
      SQLALCHEMY_DATABASE_URI: "mysql+pymysql://backend:backend-password@dealershipdb/DealershipDB?ssl_ca=/app/server-ca.pem&ssl_cert=/app/client-cert.pem&ssl_key=/app/client-key.pem"

volumes:
  mysql_data:
